"""
This type stub file was generated by pyright.
"""

import enum

"""
This type stub file was generated by pyright.
"""
class BuiltInLayouts(enum.Enum):
    """The types of layouts bundled with Shuffleboard.

    ::

        myList = (
            Shuffleboard.getTab("My Tab")
            .getLayout(BuiltinLayouts.kList, "My List")
        )
    """
    kList = ...
    kGrid = ...


