"""
This type stub file was generated by pyright.
"""

import enum

"""
This type stub file was generated by pyright.
"""
__all__ = ["EventImportance"]
class EventImportance(enum.Enum):
    """
    The importance of an event marker in Shuffleboard.  The exact meaning 
    of each importance level is up for interpretation on a team-to-team basis, 
    but users should follow the general guidelines of the various importance 
    levels.  The examples given are for reference and may be ignored or 
    considered to be more or less important from team to team.
    """
    kTrivial = ...
    kLow = ...
    kNormal = ...
    kHigh = ...
    kCritical = ...


