"""
This type stub file was generated by pyright.
"""

from networktables.networktable import NetworkTable
from .component import ShuffleboardComponent
from .container import ShuffleboardContainer

"""
This type stub file was generated by pyright.
"""
class ShuffleboardLayout(ShuffleboardComponent, ShuffleboardContainer):
    def __init__(self, parent: ShuffleboardContainer, name: str, type: str):
        ...
    
    def buildInto(self, parentTable: NetworkTable, metaTable: NetworkTable) -> None:
        ...
    


