"""
This type stub file was generated by pyright.
"""

from .container import ShuffleboardContainer
from .root import ShuffleboardRoot

"""
This type stub file was generated by pyright.
"""
class ShuffleboardTab(ShuffleboardContainer):
    def __init__(self, root: ShuffleboardRoot, title: str):
        self.root = ...
        self.title = ...
    
    def getTitle(self) -> str:
        ...
    
    def getRoot(self) -> ShuffleboardRoot:
        ...
    
    def buildInto(self, parentTable, metaTable) -> None:
        ...
    


