"""
This type stub file was generated by pyright.
"""

from collections import namedtuple

"""
This type stub file was generated by pyright.
"""
__all__ = ["AccumulatorResult"]
AccumulatorResult = namedtuple("AccumulatorResult", ["value", "count"])
