"""
This type stub file was generated by pyright.
"""

import enum
from typing import Tuple
from .spi import SPI
from .sendablebase import SendableBase
from .sendablebuilder import SendableBuilder

"""
This type stub file was generated by pyright.
"""
__all__ = ["ADXL345_SPI"]
class ADXL345_SPI(SendableBase):
    """
        ADXL345 accelerometer device via spi
        
        .. not_implemented: init
    """
    kPowerCtlRegister = ...
    kDataFormatRegister = ...
    kDataRegister = ...
    kGsPerLSB = ...
    kAddress_Read = ...
    kAddress_MultiByte = ...
    kPowerCtl_Link = ...
    kPowerCtl_AutoSleep = ...
    kPowerCtl_Measure = ...
    kPowerCtl_Sleep = ...
    kDataFormat_SelfTest = ...
    kDataFormat_SPI = ...
    kDataFormat_IntInvert = ...
    kDataFormat_FullRes = ...
    kDataFormat_Justify = ...
    Range = ...
    class Axes(enum.IntEnum):
        kX = ...
        kY = ...
        kZ = ...
    
    
    def __init__(self, port: SPI.Port, range: Range) -> None:
        """Constructor. Use this when the device is the first/only device on
        the bus

        :param port: The SPI port that the accelerometer is connected to
        :param range: The range (+ or -) that the accelerometer will measure.
        """
        self.spi = ...
    
    def close(self) -> None:
        ...
    
    def setRange(self, range: Range) -> None:
        """Set the measuring range of the accelerometer.

        :param range: The maximum acceleration, positive or negative, that
                      the accelerometer will measure.
        """
        ...
    
    def getX(self) -> float:
        """Get the x axis acceleration

        :returns: The acceleration along the x axis in g-forces
        """
        ...
    
    def getY(self) -> float:
        """Get the y axis acceleration

        :returns: The acceleration along the y axis in g-forces
        """
        ...
    
    def getZ(self) -> float:
        """Get the z axis acceleration

        :returns: The acceleration along the z axis in g-forces
        """
        ...
    
    def getAcceleration(self, axis: Axes) -> float:
        """Get the acceleration of one axis in Gs.

        :param axis: The axis to read from.
        :returns: An object containing the acceleration measured on each axis of the ADXL345 in Gs.
        """
        ...
    
    def getAccelerations(self) -> Tuple[float, float, float]:
        """Get the acceleration of all axes in Gs.

        :returns: X,Y,Z tuple of acceleration measured on all axes of the
                  ADXL345 in Gs.
        """
        ...
    
    def _updateValues(self) -> None:
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        ...
    


