"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from .analoginput import AnalogInput
from .gyrobase import GyroBase

"""
This type stub file was generated by pyright.
"""
__all__ = ["AnalogGyro"]
class AnalogGyro(GyroBase):
    """Interface to a gyro device via an :class:`.AnalogInput`
    
    Use a rate gyro to return the robots heading relative to a starting
    position.  The Gyro class tracks the robots heading based on the starting
    position. As the robot rotates the new heading is computed by integrating
    the rate of rotation returned by the sensor. When the class is
    instantiated, it does a short calibration routine where it samples the
    gyro while at rest to determine the default offset. This is subtracted
    from each sample to determine the heading.

    .. not_implemented: initGyro
    """
    kOversampleBits = ...
    kAverageBits = ...
    kSamplesPerSecond = ...
    kCalibrationSampleTime = ...
    kDefaultVoltsPerDegreePerSecond = ...
    PIDSourceType = ...
    def __init__(self, channel: Union[AnalogInput, int], center: Optional[int] = ..., offset: Optional[float] = ...) -> None:
        """Gyro constructor.

        Also initializes the gyro. Calibrate the gyro by running for a number
        of samples and computing the center value. Then use the
        center value as the Accumulator center value for subsequent
        measurements. It's important to make sure that the robot is not
        moving while the centering calculations are in progress, this is
        typically done when the robot is first turned on while it's sitting
        at rest before the competition starts.

        :param channel: The analog channel index or AnalogInput object that
            the gyro is connected to. Gyros can only be used on on-board channels 0-1.
        :param center: Preset uncalibrated value to use as the accumulator center value
        :param offset: Preset uncalibrated value to use as the gyro offset
        """
        self.analog = ...
        self.gyroHandle = ...
    
    def calibrate(self) -> None:
        """:see: :meth:`.Gyro.calibrate`"""
        ...
    
    def reset(self) -> None:
        """:see: :meth:`.Gyro.reset`"""
        ...
    
    def close(self) -> None:
        """:see: :meth:`.Gyro.close`"""
        self.gyroHandle = ...
    
    def getAngle(self) -> float:
        """:see: :meth:`.Gyro.getAngle`"""
        ...
    
    def getRate(self) -> float:
        """:see: :meth:`.Gyro.getRate`"""
        ...
    
    def getOffset(self) -> float:
        """Return the gyro offset value set during calibration to
        use as a future preset
        
        :returns: the current offset value
        """
        ...
    
    def getCenter(self) -> int:
        """Return the gyro center value set during calibration to
        use as a future preset
        
        :returns: the current center value
        """
        ...
    
    def setSensitivity(self, voltsPerDegreePerSecond: float) -> None:
        """Set the gyro sensitivity. This takes the number of
        volts/degree/second sensitivity of the gyro and uses it in subsequent
        calculations to allow the code to work with multiple gyros. This value
        is typically found in the gyro datasheet.

        :param voltsPerDegreePerSecond:
            The sensitivity in Volts/degree/second
        """
        ...
    
    def setDeadband(self, volts: float) -> None:
        """Set the size of the neutral zone.  Any voltage from the gyro less
        than this amount from the center is considered stationary.  Setting a
        deadband will decrease the amount of drift when the gyro isn't
        rotating, but will make it less accurate.

        :param volts: The size of the deadband in volts
        """
        ...
    


