"""
This type stub file was generated by pyright.
"""

from .sendablebuilder import SendableBuilder
from .sendablebase import SendableBase

"""
This type stub file was generated by pyright.
"""
__all__ = ["BuiltInAccelerometer"]
class BuiltInAccelerometer(SendableBase):
    """Built-in accelerometer device

    This class allows access to the roboRIO's internal accelerometer.
    """
    Range = ...
    def __init__(self, range: Range = ...) -> None:
        """Constructor.
        
        :param range: The range the accelerometer will measure.  Defaults to
            +/-8g if unspecified.
        """
        self.xEntry = ...
        self.yEntry = ...
        self.zEntry = ...
    
    def setRange(self, range: Range) -> None:
        """Set the measuring range of the accelerometer.

        :param range: The maximum acceleration, positive or negative, that
                      the accelerometer will measure.
        """
        ...
    
    def getX(self) -> float:
        """
           :returns: The acceleration of the roboRIO along the X axis in
                     g-forces
        """
        ...
    
    def getY(self) -> float:
        """
           :returns: The acceleration of the roboRIO along the Y axis in
                     g-forces
        """
        ...
    
    def getZ(self) -> float:
        """
           :returns: The acceleration of the roboRIO along the Z axis in
                     g-forces
        """
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        ...
    


