"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__all__ = ["ControllerPower"]
class ControllerPower:
    """Old Controller PR class.

    .. deprecated:: 2018.0.0
        Use RobotController class instead
    """
    @staticmethod
    def getInputVoltage() -> float:
        """
            Get the input voltage to the robot controller

            :returns: The controller input voltage value in Volts
        """
        ...
    
    @staticmethod
    def getInputCurrent() -> float:
        """
            Get the input current to the robot controller

            :returns: The controller input current value in Amps
        """
        ...
    
    @staticmethod
    def getVoltage3V3() -> float:
        """
            Get the voltage of the 3.3V rail

            :returns: The controller 3.3V rail voltage value in Volts
        """
        ...
    
    @staticmethod
    def getCurrent3V3() -> float:
        """
            Get the current output of the 3.3V rail

            :returns: The controller 3.3V rail output current value in Amps
        """
        ...
    
    @staticmethod
    def getEnabled3V3() -> bool:
        """
            Get the enabled state of the 3.3V rail. The rail may be
            disabled due to a controller brownout, a short circuit on the
            rail, or controller over-voltage

            :returns: True if enabled, False otherwise
        """
        ...
    
    @staticmethod
    def getFaultCount3V3() -> int:
        """
            Get the count of the total current faults on the 3.3V rail since
            the controller has booted

            :returns: The number of faults
        """
        ...
    
    @staticmethod
    def getVoltage5V() -> float:
        """
            Get the voltage of the 5V rail


            :returns: The controller 5V rail voltage value in Volts
        """
        ...
    
    @staticmethod
    def getCurrent5V() -> float:
        """
            Get the current output of the 5V rail

            :returns: The controller 5V rail output current value in Amps
        """
        ...
    
    @staticmethod
    def getEnabled5V() -> bool:
        """
            Get the enabled state of the 5V rail. The rail may be disabled
            due to a controller brownout, a short circuit on the rail, or
            controller over-voltage

            :returns: True if enabled, False otherwise
        """
        ...
    
    @staticmethod
    def getFaultCount5V() -> int:
        """
            Get the count of the total current faults on the 5V rail since
            the controller has booted

            :returns: The number of faults
        """
        ...
    
    @staticmethod
    def getVoltage6V() -> float:
        """
            Get the voltage of the 6V rail

            :returns: The controller 6V rail voltage value in Volts
        """
        ...
    
    @staticmethod
    def getCurrent6V() -> float:
        """
            Get the current output of the 6V rail

            :returns: The controller 6V rail output current value in Amps
        """
        ...
    
    @staticmethod
    def getEnabled6V() -> bool:
        """
            Get the enabled state of the 6V rail. The rail may be disabled
            due to a controller brownout, a short circuit on the rail, or
            controller over-voltage

            :returns: True if enabled, False otherwise
        """
        ...
    
    @staticmethod
    def getFaultCount6V() -> int:
        """
            Get the count of the total current faults on the 6V rail since
            the controller has booted

            :returns: The number of faults
        """
        ...
    


