"""
This type stub file was generated by pyright.
"""

import enum
from typing import Union
from .digitalinput import DigitalInput
from .sendablebase import SendableBase
from .sendablebuilder import SendableBuilder

"""
This type stub file was generated by pyright.
"""
__all__ = ["Encoder"]
def _freeEncoder(encoder: Encoder) -> None:
    ...

class Encoder(SendableBase):
    """Class to read quadrature encoders.
    
    Quadrature encoders are devices that count
    shaft rotation and can sense direction. The output of the Encoder class
    is an integer that can count either up or down, and can go negative for
    reverse direction counting. When creating Encoders, a direction can be
    supplied that inverts the sense of the output to make code more readable
    if the encoder is mounted such that forward movement generates negative
    values. Quadrature encoders have two digital outputs, an A Channel and a
    B Channel, that are out of phase with each other for direction sensing.

    All encoders will immediately start counting - reset() them if you need
    them to be zeroed before use.

    Instance variables:
    
    - aSource: The A phase of the quad encoder
    - bSource: The B phase of the quad encoder
    - indexSource: The index source (available on some encoders)
    """
    class IndexingType(enum.IntEnum):
        kResetWhileHigh = ...
        kResetWhileLow = ...
        kResetOnFallingEdge = ...
        kResetOnRisingEdge = ...
    
    
    EncodingType = ...
    PIDSourceType = ...
    def __init__(self, *args, **kwargs) -> None:
        """Encoder constructor. Construct a Encoder given a and b channels
        and optionally an index channel.

        The encoder will start counting immediately.

        The a, b, and optional index channel arguments may be either channel
        numbers or :class:`.DigitalSource` sources. There may also be a boolean
        reverseDirection, and an encodingType according to the following
        list.
        
        - aSource, bSource
        - aSource, bSource, reverseDirection
        - aSource, bSource, reverseDirection, encodingType
        - aSource, bSource, indexSource, reverseDirection
        - aSource, bSource, indexSource
        - aChannel, bChannel
        - aChannel, bChannel, reverseDirection
        - aChannel, bChannel, reverseDirection, encodingType
        - aChannel, bChannel, indexChannel, reverseDirection
        - aChannel, bChannel, indexChannel

        For positional arguments, if the passed object has a
        `getPortHandleForRouting` function, it is assumed to be a DigitalSource.

        Alternatively, sources and/or channels may be passed as keyword
        arguments.  The behavior of specifying both a source and a number
        for the same channel is undefined, as is passing both a positional
        and a keyword argument for the same channel.

        In addition, keyword parameters may be provided for reverseDirection
        and inputType.

        :param aSource: The source that should be used for the a channel.
        :type aSource: :class:`.DigitalSource`
        :param bSource: The source that should be used for the b channel.
        :type bSource: :class:`.DigitalSource`
        :param indexSource: The source that should be used for the index
            channel.
        :type indexSource: :class:`.DigitalSource`
        :param aChannel: The digital input index that should be used for
            the a channel.
        :type aChannel: int
        :param bChannel: The digital input index that should be used for
            the b channel.
        :type bChannel: int
        :param indexChannel: The digital input index that should be used
            for the index channel.
        :type indexChannel: int
        :param reverseDirection:
            Represents the orientation of the encoder and inverts the
            output values if necessary so forward represents positive
            values.  Defaults to False if unspecified.
        :type reverseDirection: bool
        :param encodingType:
            Either k1X, k2X, or k4X to indicate 1X, 2X or 4X decoding. If
            4X is selected, then an encoder FPGA object is used and the
            returned counts will be 4x the encoder spec'd value since all
            rising and falling edges are counted. If 1X or 2X are selected
            then a counter object will be used and the returned value will
            either exactly match the spec'd count or be double (2x) the
            spec'd count.  Defaults to k4X if unspecified.
        :type encodingType: :class:`Encoder.EncodingType`
        """
        self.allocatedA = ...
        self.allocatedB = ...
        self.allocatedIndex = ...
        self.aSource = ...
        self.bSource = ...
        self.indexSource = ...
        self.encodingType = ...
        self.pidSource = ...
        self.encoder = ...
        self.counter = ...
        self.speedEntry = ...
        self.distanceEntry = ...
        self.distancePerTickEntry = ...
        self.encoder = ...
        self.index = ...
    
    def getFPGAIndex(self) -> int:
        """
        Get the FPGA Index of the encoder

        :returns: The Encoder's FPGA index
        """
        ...
    
    def getEncodingScale(self) -> int:
        """
        :returns: The encoding scale factor 1x, 2x, or 4x, per the requested
            encodingType. Used to divide raw edge counts down to spec'd counts.
        """
        ...
    
    def close(self) -> None:
        """Free the resources used by this object."""
        self.aSource = ...
        self.bSource = ...
        self.indexSource = ...
        self.encoder = ...
    
    def getRaw(self) -> int:
        """Gets the raw value from the encoder. The raw value is the actual
        count unscaled by the 1x, 2x, or 4x scale factor.

        :returns: Current raw count from the encoder
        """
        ...
    
    def get(self) -> int:
        """Gets the current count. Returns the current count on the Encoder.
        This method compensates for the decoding type.

        :returns: Current count from the Encoder adjusted for the 1x, 2x, or
            4x scale factor.
        """
        ...
    
    def reset(self) -> None:
        """Reset the Encoder distance to zero. Resets the current count to
        zero on the encoder.
        """
        ...
    
    def getPeriod(self) -> float:
        """Returns the period of the most recent pulse. Returns the period of
        the most recent Encoder pulse in seconds. This method compensates for
        the decoding type.

        .. deprecated::
            Use :func:`getRate` in favor of this method. This returns unscaled
            periods and :func:`getRate` scales using value from
            :func:`getDistancePerPulse`.

        :returns: Period in seconds of the most recent pulse.
        """
        ...
    
    def setMaxPeriod(self, maxPeriod: float) -> None:
        """Sets the maximum period for stopped detection. Sets the value that
        represents the maximum period of the Encoder before it will assume
        that the attached device is stopped. This timeout allows users to
        determine if the wheels or other shaft has stopped rotating. This
        method compensates for the decoding type.

        :param maxPeriod: The maximum time between rising and falling edges
            before the FPGA will report the device stopped. This is expressed
            in seconds.
        """
        ...
    
    def getStopped(self) -> bool:
        """Determine if the encoder is stopped. Using the MaxPeriod value, a
        boolean is returned that is True if the encoder is considered stopped
        and False if it is still moving. A stopped encoder is one where the
        most recent pulse width exceeds the MaxPeriod.

        :returns: True if the encoder is considered stopped.
        """
        ...
    
    def getDirection(self) -> bool:
        """The last direction the encoder value changed.

        :returns: The last direction the encoder value changed.
        """
        ...
    
    def getDistance(self) -> float:
        """Get the distance the robot has driven since the last reset.

        :returns: The distance driven since the last reset as scaled by the
            value from :func:`setDistancePerPulse`.
        """
        ...
    
    def getRate(self) -> float:
        """Get the current rate of the encoder. Units are distance per second
        as scaled by the value from :func:`setDistancePerPulse`.

        :returns: The current rate of the encoder.
        """
        ...
    
    def setMinRate(self, minRate: float) -> None:
        """Set the minimum rate of the device before the hardware reports it
        stopped.

        :param minRate: The minimum rate. The units are in distance per
            second as scaled by the value from :func:`setDistancePerPulse`.
        """
        ...
    
    def setDistancePerPulse(self, distancePerPulse: float) -> None:
        """Set the distance per pulse for this encoder. This sets the
        multiplier used to determine the distance driven based on the count
        value from the encoder. Do not include the decoding type in this
        scale. The library already compensates for the decoding type. Set
        this value based on the encoder's rated Pulses per Revolution and
        factor in gearing reductions following the encoder shaft. This
        distance can be in any units you like, linear or angular.

        :param distancePerPulse: The scale factor that will be used to convert
            pulses to useful units.
        """
        ...
    
    def getDistancePerPulse(self) -> float:
        """ 
        Get the distance per pulse for this encoder.

        :returns: The scale factor that will be used to convert pulses to useful units.
        """
        ...
    
    def setReverseDirection(self, reverseDirection: bool) -> None:
        """Set the direction sensing for this encoder. This sets the direction
        sensing on the encoder so that it could count in the correct software
        direction regardless of the mounting.

        :param reverseDirection: True if the encoder direction should be
            reversed
        """
        ...
    
    def setSamplesToAverage(self, samplesToAverage: int) -> None:
        """Set the Samples to Average which specifies the number of samples
        of the timer to average when calculating the period. Perform averaging
        to account for mechanical imperfections or as oversampling to increase
        resolution.

        TODO: Should this raise an exception, so that the user has to
        deal with giving an incorrect value?

        :param samplesToAverage: The number of samples to average from 1 to
            127.
        """
        ...
    
    def getSamplesToAverage(self) -> int:
        """Get the Samples to Average which specifies the number of samples
        of the timer to average when calculating the period. Perform averaging
        to account for mechanical imperfections or as oversampling to increase
        resolution.

        :returns: The number of samples being averaged (from 1 to 127)
        """
        ...
    
    def setPIDSourceType(self, pidSource: PIDSourceType) -> None:
        """Set which parameter of the encoder you are using as a process
        control variable. The encoder class supports the rate and distance
        parameters.

        :param pidSource: An enum to select the parameter.
        """
        self.pidSource = ...
    
    def getPIDSourceType(self) -> PIDSourceType:
        ...
    
    def pidGet(self) -> float:
        """Implement the PIDSource interface.

         :returns: The current value of the selected source parameter.
        """
        ...
    
    def setIndexSource(self, source: Union[int, DigitalInput], indexing_type: IndexingType = ...) -> None:
        """
        Set the index source for the encoder. When this source rises, the encoder count automatically resets.

        :param source: Either an initialized DigitalSource or a DIO channel number
        :param indexing_type: The state that will cause the encoder to reset
        """
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        ...
    


