"""
This type stub file was generated by pyright.
"""

from .interfaces.pidsource import PIDSource

"""
This type stub file was generated by pyright.
"""
__all__ = ["Filter"]
class Filter:
    """Superclass for filters"""
    def __init__(self, source: PIDSource) -> None:
        """Constructor.
        
        :param source:
        """
        self.source = ...
    
    def setPIDSourceType(self, pidSourceType: PIDSource.PIDSourceType) -> None:
        ...
    
    def getPIDSourceType(self) -> PIDSource.PIDSourceType:
        ...
    
    def pidGet(self) -> float:
        ...
    
    def get(self) -> float:
        """Returns the current filter estimate without also inserting new data as
        :meth:`pidGet` would do.
        
        :returns: The current filter estimate
        """
        ...
    
    def reset(self) -> None:
        """Reset the filter state"""
        ...
    
    def pidGetSource(self) -> float:
        """Calls PIDGet() of source
        
        :returns: Current value of source
        """
        ...
    


