"""
This type stub file was generated by pyright.
"""

from .counter import Counter
from .sendablebuilder import SendableBuilder

"""
This type stub file was generated by pyright.
"""
__all__ = ["GearTooth"]
class GearTooth(Counter):
    """Interface to the gear tooth sensor supplied by FIRST
    
    Currently there is no reverse sensing on the gear tooth sensor, but in
    future versions we might implement the necessary timing in the FPGA to
    sense direction.
    """
    kGearToothThreshold = ...
    def enableDirectionSensing(self, directionSensitive: bool) -> None:
        ...
    
    def __init__(self, channel: int, directionSensitive: bool = ...) -> None:
        """Construct a GearTooth sensor.

        :param channel: The DIO channel index or DigitalSource that the sensor
            is connected to.
        :param directionSensitive: True to enable the pulse length decoding in
            hardware to specify count direction.  Defaults to False.
        """
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        ...
    


