"""
This type stub file was generated by pyright.
"""

from .sendablebuilder import SendableBuilder
from .sendablebase import SendableBase

"""
This type stub file was generated by pyright.
"""
__all__ = ["PIDBase"]
class PIDBase(SendableBase):
    """Class implements a PID Control Loop.

    Creates a separate thread which reads the given PIDSource and takes care of the integral
    calculations, as well as writing the given PIDOutput.

    This feedback controller runs in discrete time, so time deltas are not used in the integral
    and derivative calculations. Therefore, the sample rate affects the controller's behavior for a
    given set of PID constants.

    """
    kDefaultPeriod = ...
    instances = ...
    PIDSourceType = ...
    def PercentageTolerance_onTarget(self, percentage: float) -> bool:
        ...
    
    def AbsoluteTolerance_onTarget(self, value: float) -> bool:
        ...
    
    def __init__(self, Kp, Ki, Kd, Kf, source, output):
        """Allocate a PID object with the given constants for P, I, D, and F

        :param Kp: the proportional coefficient
        :type  Kp: float or int
        :param Ki: the integral coefficient
        :type  Ki: float or int
        :param Kd: the derivative coefficient
        :type  Kd: float or int
        :param Kf: the feed forward term
        :type  Kf: float or int
        :param source: Called to get values
        :type  source: A function, or an object that implements :class:`.PIDSource`
        :param output: Receives the output percentage
        :type  output: A function, or an object that implements :class:`.PIDOutput`
        """
        self.P = ...
        self.I = ...
        self.D = ...
        self.F = ...
        self.pidOutput = ...
        self.origSource = ...
        self.filter = ...
        self.pidInput = ...
        self.pidInput = ...
        self.maximumOutput = ...
        self.minimumOutput = ...
        self.maximumInput = ...
        self.minimumInput = ...
        self.inputRange = ...
        self.continuous = ...
        self.enabled = ...
        self.prevError = ...
        self.totalError = ...
        self.setpoint = ...
        self.prevSetpoint = ...
        self.error = ...
        self.result = ...
        self.mutex = ...
        self.pidWriteMutex = ...
        self.setpointTimer = ...
    
    def _calculate(self) -> None:
        """Read the input, calculate the output accordingly, and write to the
        output.  This should only be called by the PIDTask and is created
        during initialization."""
        ...
    
    def calculateFeedForward(self) -> float:
        """Calculate the feed forward term

        Both of the provided feed forward calculations are velocity feed forwards.
        If a different feed forward calculation is desired, the user can override
        this function and provide his or her own. This function  does no
        synchronization because the PIDController class only calls it in
        synchronized code, so be careful if calling it oneself.

        If a velocity PID controller is being used, the F term should be set to 1
        over the maximum setpoint for the output. If a position PID controller is
        being used, the F term should be set to 1 over the maximum speed for the
        output measured in setpoint units per this controller's update period (see
        the default period in this class's constructor).
        """
        ...
    
    def setPID(self, p: float, i: float, d: float, f: float = ...) -> None:
        """Set the PID Controller gain parameters.
        Set the proportional, integral, and differential coefficients.

        :param p: Proportional coefficient
        :param i: Integral coefficient
        :param d: Differential coefficient
        :param f: Feed forward coefficient (optional, default is 0.0)
        """
        ...
    
    def setP(self, p) -> None:
        """
        Set the Proportional coefficient of the PID controller gain.

        :param p: Proportional coefficient
        """
        ...
    
    def setI(self, i) -> None:
        """
        Set the Integral coefficient of the PID controller gain.

        :param i: Integral coefficient
        """
        ...
    
    def setD(self, d) -> None:
        """
        Set the Differential coefficient of the PID controller gain.

        :param d: differential coefficient
        """
        ...
    
    def setF(self, f) -> None:
        """
        Set the Feed forward coefficient of the PID controller gain.

        :param f: feed forward coefficient
        """
        ...
    
    def getP(self) -> float:
        """Get the Proportional coefficient.

        :returns: proportional coefficient
        """
        ...
    
    def getI(self) -> float:
        """Get the Integral coefficient

        :returns: integral coefficient
        """
        ...
    
    def getD(self) -> float:
        """Get the Differential coefficient.

        :returns: differential coefficient
        """
        ...
    
    def getF(self) -> float:
        """Get the Feed forward coefficient.

        :returns: feed forward coefficient
        """
        ...
    
    def get(self) -> float:
        """Return the current PID result.
        This is always centered on zero and constrained the the max and min
        outs.

        :returns: the latest calculated output
        """
        ...
    
    def setContinuous(self, continuous: bool = ...) -> None:
        """Set the PID controller to consider the input to be continuous.
        Rather then using the max and min input range as constraints, it considers them
        to be the same point and automatically calculates the shortest route
        to the setpoint.

        :param continuous: Set to True turns on continuous, False turns off
            continuous
        """
        ...
    
    def setInputRange(self, minimumInput: float, maximumInput: float) -> None:
        """Sets the maximum and minimum values expected from the input.

        :param minimumInput: the minimum percentage expected from the input
        :param maximumInput: the maximum percentage expected from the output
        """
        ...
    
    def setOutputRange(self, minimumOutput: float, maximumOutput: float) -> None:
        """Sets the minimum and maximum values to write.

        :param minimumOutput: the minimum percentage to write to the output
        :param maximumOutput: the maximum percentage to write to the output
        """
        ...
    
    def setSetpoint(self, setpoint: float) -> None:
        """Set the setpoint for the PIDController.

        :param setpoint: the desired setpoint
        """
        ...
    
    def getSetpoint(self) -> float:
        """Returns the current setpoint of the PIDController.

        :returns: the current setpoint
        """
        ...
    
    def getDeltaSetpoint(self) -> float:
        """Returns the change in setpoint over time of the PIDController

        :returns: the change in setpoint over time
        """
        ...
    
    def getError(self) -> float:
        """Returns the current difference of the input from the setpoint.

        :return: the current error
        """
        ...
    
    def getAvgError(self) -> float:
        """
        Returns the current difference of the error over the past few iterations. You can specify the
        number of iterations to average with setToleranceBuffer() (defaults to 1). getAvgError() is
        used for the onTarget() function.

        .. deprecated :: 2018.0.0
            Use getError(), which is now already filtered.

        :returns: the current average of the error
        """
        ...
    
    def setPIDSourceType(self, pidSourceType: PIDSourceType) -> None:
        """Sets what type of input the PID controller will use

        :param pidSourceType: the type of input
        """
        ...
    
    def getPIDSourceType(self) -> PIDSourceType:
        """Returns the type of input the PID controller is using

        :returns: the PID controller input type
        """
        ...
    
    def setAbsoluteTolerance(self, absvalue: float) -> None:
        """Set the absolute error which is considered tolerable for use with
        :func:`onTarget`.

        :param absvalue: absolute error which is tolerable in the units of the
            input object
        """
        ...
    
    def setPercentTolerance(self, percentage: float) -> None:
        """Set the percentage error which is considered tolerable for use with
        :func:`onTarget`. (Input of 15.0 = 15 percent)

        :param percentage: percent error which is tolerable
        """
        ...
    
    def setToleranceBuffer(self, bufLength: int) -> None:
        """Set the number of previous error samples to average for tolerancing. When
        determining whether a mechanism is on target, the user may want to use a
        rolling average of previous measurements instead of a precise position or
        velocity. This is useful for noisy sensors which return a few erroneous
        measurements when the mechanism is on target. However, the mechanism will
        not register as on target for at least the specified bufLength cycles.

        :param bufLength: Number of previous cycles to average.
        :type bufLength: int

        .. deprecated:: 2018.0.0
            Use a LinearDigitalFilter as the input
        """
        ...
    
    def onTarget(self) -> bool:
        """Return True if the error is within the percentage of the total input
        range, determined by setTolerance. This assumes that the maximum and
        minimum input were set using :func:`setInput`.

        :returns: True if the error is less than the tolerance
        """
        ...
    
    def reset(self) -> None:
        """Reset the previous error, the integral term, and disable the controller.

        """
        ...
    
    def pidWrite(self, output: float) -> None:
        """Passes the output directly to setSetpoint().

        PIDControllers can be nested by passing a PIDController as another PIDController's output.
        In that case, the output of the parent controller becomes the input (i.e., the reference) of
        the child.

        It is the caller's responsibility to put the data into a valid form for setSetpoint().

        """
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        ...
    
    def getContinuousError(self, error: float) -> float:
        """
        Wraps error around for continuous inputs. The original error is
        returned if continuous mode is disabled. This is an unsynchronized
        function.

        :param error: The current error of the PID controller.
        :return: Error for continuous inputs.
        """
        ...
    
    def clamp(self, value: float, low: float, high: float) -> float:
        ...
    


