"""
This type stub file was generated by pyright.
"""

from .pwm import PWM
from .sendablebuilder import SendableBuilder

"""
This type stub file was generated by pyright.
"""
__all__ = ["PWMSpeedController"]
class PWMSpeedController(PWM):
    """
        Common base class for all PWM Speed Controllers.
    """
    def __init__(self, channel: int) -> None:
        self.isInverted = ...
    
    def getDescription(self):
        ...
    
    def set(self, speed: float) -> None:
        """Set the PWM value.

        The PWM value is set using a range of -1.0 to 1.0, appropriately
        scaling the value for the FPGA.

        :param speed: The speed to set.  Value should be between -1.0 and 1.0.
        """
        ...
    
    def setInverted(self, isInverted: bool) -> None:
        """
        Common interface for inverting the direction of a speed controller.

        :param isInverted: The state of inversion (True is inverted).
        """
        self.isInverted = ...
    
    def getInverted(self) -> bool:
        """
        Common interface for inverting the direction of a speed controller.

        :returns: The state of inversion (True is inverted)
        """
        ...
    
    def get(self) -> float:
        """Get the recently set value of the PWM.

        :returns: The most recently set value for the PWM between -1.0 and 1.0.
        """
        ...
    
    def disable(self):
        ...
    
    def pidWrite(self, output: float) -> None:
        """Write out the PID value as seen in the PIDOutput base object.

        :param output: Write out the PWM value as was found in the
            :class:`PIDController`.
        """
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        ...
    


