"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__all__ = ["RobotState"]
class RobotState:
    """Provides an interface to determine the current operating state of the
    robot code.
    """
    @staticmethod
    def isDisabled() -> bool:
        ...
    
    @staticmethod
    def isEnabled() -> bool:
        ...
    
    @staticmethod
    def isOperatorControl() -> bool:
        ...
    
    @staticmethod
    def isAutonomous() -> bool:
        ...
    
    @staticmethod
    def isTest() -> bool:
        ...
    


