"""
This type stub file was generated by pyright.
"""

from .robotbase import RobotBase

"""
This type stub file was generated by pyright.
"""
__all__ = ["SampleRobot"]
class SampleRobot(RobotBase):
    """A simple robot base class that knows the standard FRC competition
    states (disabled, autonomous, or operator controlled).

    You can build a simple robot program off of this by overriding the
    :meth:`robotinit`, :meth:`disabled`, :meth:`autonomous` and
    :meth:`operatorControl` methods. The :meth:`startCompetition` method
    will call these methods (sometimes repeatedly) depending on the state
    of the competition.

    Alternatively you can override the :meth:`robotMain` method and manage all
    aspects of the robot yourself (not recommended).
    
    .. warning::
        While it may look like a good choice to use for your code
        if you're inexperienced, don't. Unless you know what you
        are doing, complex code will be much more difficult under
        this system. Use :class:`.TimedRobot` or command based
        instead if you're new.

    .. deprecated:: 2018.0.0
    """
    logger = ...
    def robotInit(self) -> None:
        """Robot-wide initialization code should go here.

        Users should override this method for default Robot-wide initialization
        which will be called when the robot is first powered on.  It will be
        called exactly 1 time.
        
        .. note:: It is simpler to override this function instead of defining
                  a constructor for your robot class
                  
        .. warning:: the Driver Station "Robot Code" light and FMS "Robot Ready"
                     indicators will be off until RobotInit() exits. Code in ``robotInit()`` that
                     waits for enable will cause the robot to never indicate that the code is
                     ready, causing the robot to be bypassed in a match.
        """
        ...
    
    def disabled(self) -> None:
        """Disabled should go here.
        Users should override this method to run code that should run while
        the field is disabled.

        Called once each time the robot enters the disabled state.
        """
        ...
    
    def autonomous(self) -> None:
        """Autonomous should go here.
        Users should add autonomous code to this method that should run while
        the field is in the autonomous period.

        Called once each time the robot enters the autonomous state.
        """
        ...
    
    def operatorControl(self) -> None:
        """Operator control (tele-operated) code should go here.
        Users should add Operator Control code to this method that should run
        while the field is in the Operator Control (tele-operated) period.

        Called once each time the robot enters the operator-controlled state.
        """
        ...
    
    def test(self) -> None:
        """Test code should go here.
        Users should add test code to this method that should run while the
        robot is in test mode.
        """
        ...
    
    def robotMain(self) -> None:
        """Robot main program for free-form programs.

        This should be overridden by user subclasses if the intent is to not
        use the autonomous() and operatorControl() methods. In that case, the
        program is responsible for sensing when to run the autonomous and
        operator control functions in their program.

        This method will be called immediately after the constructor is
        called. If it has not been overridden by a user subclass (i.e. the
        default version runs), then the robotInit(), disabled(), autonomous()
        and operatorControl() methods will be called.
        
        If you override this function, you must call ``hal.HALNetworkCommunicationObserveUserProgramStarting()``
        to indicate that your robot is ready to be enabled, as it will not
        be called for you.
        
        .. warning:: Nobody actually wants to override this function. Neither
                     do you.
        
        """
        ...
    
    def startCompetition(self) -> None:
        """Start a competition.
        This code tracks the order of the field starting to ensure that
        everything happens in the right order. Repeatedly run the correct
        method, either Autonomous or OperatorControl when the robot is
        enabled. After running the correct method, wait for some state to
        change, either the other mode starts or the robot is disabled. Then
        go back and wait for the robot to be enabled again.
        """
        ...
    


