"""
This type stub file was generated by pyright.
"""

from typing import Optional
from .sendablebuilder import SendableBuilder

"""
This type stub file was generated by pyright.
"""
__all__ = ["Sendable"]
class Sendable:
    """The base interface for objects that can be sent over the network
    through network tables"""
    def getName(self) -> str:
        """
        Gets the name of this Sendable object.

        :returns: Name
        """
        ...
    
    def setName(self, subsystem: str, name: Optional[str] = ...) -> None:
        """
        Sets the name (and optionally the subsystem name) of this Sendable object.

        This may be called with two different sets of parameters:

        - name
        - subsystem, name

        :param str subsystem: subsystem name
        :param str name: Name
        """
        ...
    
    def _setName(self, name: str) -> None:
        """Sets the name of this Sendable object."""
        ...
    
    def _setNameAndSubsystem(self, subsystem: str, name: str) -> None:
        """
        Sets both the subsystem name and device name of this Sendable object.

        :param subsystem: subsystem name
        :param name: Name
        """
        ...
    
    def getSubsystem(self) -> str:
        """
        Gets the subsystem name of this Sendable object.

        :returns: subsystem name
        """
        ...
    
    def setSubsystem(self, subsystem: str) -> None:
        """
        Sets the subsystem name of this Sendable object.

        :param subsystem: subsystem name
        """
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        """
        Initializes this Sendable object.

        :param builder: sendable builder
        """
        ...
    


