"""
This type stub file was generated by pyright.
"""

from .sendable import Sendable

"""
This type stub file was generated by pyright.
"""
__all__ = ["SendableBase"]
class SendableBase(Sendable):
    """
    Base class for all sensors. Stores most recent status information as well as containing utility
    functions for checking channels and error processing.
    """
    def __init__(self, addLiveWindow: bool = ...) -> None:
        """
        Creates an instance of the sensor base.
   
        :param addLiveWindow: if true, add this Sendable to LiveWindow
        """
        self.name = ...
        self.subsystem = ...
        self.mutex = ...
    
    def free(self) -> None:
        """
        Free the resources used by this object.

        .. deprecated:: 2019.0.0
            Use close instead 
        """
        ...
    
    def close(self):
        """
        Free the resources used by this object.
        """
        ...
    
    def getName(self) -> str:
        ...
    
    def _setName(self, name: str) -> None:
        ...
    
    def setName(self, *args, **kwargs) -> None:
        """
        Sets the name of this Sendable object.

        Arguments can be structured as follows:

        - name
        - subsystem, name
        - moduleType, channel
        - moduleType, moduleNumber, channel

        :param name: name
        :type name: str
        :param subsystem: subsystem name
        :type subsystem: str
        :param moduleType: A string that defines the module name in the label for the value
        :type moduleType: str
        :param channel: The channel number the device is plugged into
        :type channel: int
        :param moduleNumber: The number of the particular module type
        :type moduleNumber: int
        """
        ...
    
    def getSubsystem(self) -> str:
        ...
    
    def setSubsystem(self, subsystem: str) -> None:
        ...
    
    def addChild(self, child: object) -> None:
        """
        Add a child component

        :param child: child component
        """
        ...
    


