"""
This type stub file was generated by pyright.
"""

from typing import Union
from .sendablebase import SendableBase

"""
This type stub file was generated by pyright.
"""
__all__ = ["SolenoidBase"]
class SolenoidBase(SendableBase):
    """SolenoidBase class is the common base class for the Solenoid and
    DoubleSolenoid classes."""
    def __init__(self, moduleNumber: int) -> None:
        """Constructor.

        :param moduleNumber: The PCM CAN ID
        """
        self.moduleNumber = ...
    
    def getAll(moduleNumber: Union[int, SolenoidBase]) -> int:
        """Read all 8 solenoids from the specified module as a
        single byte.

        :param moduleNumber: in a static context, the module number to read. otherwise don't provide it.
        :returns: The current value of all 8 solenoids on the module.
        """
        ...
    
    def getPCMSolenoidBlackList(moduleNumber: Union[int, SolenoidBase]) -> int:
        """
        Reads complete solenoid blacklist for all 8 solenoids as a single byte.
            If a solenoid is shorted, it is added to the blacklist and
            disabled until power cycle, or until faults are cleared. See
            :meth:`clearAllPCMStickyFaults`

        :param moduleNumber: in a static context, the module number to read. otherwise don't provide it.
        :returns: The solenoid blacklist of all 8 solenoids on the module.
        """
        ...
    
    def getPCMSolenoidVoltageStickyFault(moduleNumber: Union[int, SolenoidBase]) -> bool:
        """
        :param moduleNumber: in a static context, the module number to read. otherwise don't provide it.
        :returns: True if PCM Sticky fault is set : The common
            highside solenoid voltage rail is too low, most likely
            a solenoid channel has been shorted.
        """
        ...
    
    def getPCMSolenoidVoltageFault(moduleNumber: Union[int, SolenoidBase]) -> bool:
        """
        :param moduleNumber: in a static context, the module number to read. otherwise don't provide it.
        :returns: True if PCM is in fault state : The common
            highside solenoid voltage rail is too low, most likely
            a solenoid channel has been shorted.
        """
        ...
    
    def clearAllPCMStickyFaults(moduleNumber: Union[int, SolenoidBase]) -> None:
        """
        Clear ALL sticky faults inside the PCM that Solenoid is wired to.

        If a sticky fault is set, then it will be persistently cleared. Compressor drive
            maybe momentarily disable while flages are being cleared. Care should be
            taken to not call this too frequently, otherwise normal compressor functionality
            may be prevented.

        If no sticky faults are set then this call will have no effect.

        :param moduleNumber: in a static context, the module number to read. otherwise don't provide it.
        """
        ...
    


