"""
This type stub file was generated by pyright.
"""

from .command import Command
from typing import Any, Optional

"""
This type stub file was generated by pyright.
"""
__all__ = ["InstantCommand"]
class InstantCommand(Command):
    """
    This command will execute once, then finish immediately afterward.

    Subclassing :class:`.InstantCommand` is shorthand for returning true from
    :meth:`.Command.isFinished`
    """
    def __init__(self, name: Optional[Any] = ..., subsystem: Optional[Any] = ..., func: Optional[Any] = ...):
        """
        Creates a new InstantCommand

        :param name:        the name for this command
        :param requirement: the subsystem this command requires
        :param func:        the function to run when :meth:`.Command.initialize` is run
        """
        self.func = ...
    
    def isFinished(self):
        ...
    
    def _initialize(self):
        """
        Trigger the stored function.

        Called just before this Command runs the first time.
        """
        ...
    


