"""
This type stub file was generated by pyright.
"""

from .command import Command
from typing import Any, Optional

"""
This type stub file was generated by pyright.
"""
__all__ = ["TimedCommand"]
class TimedCommand(Command):
    """A command that runs for a set period of time."""
    def __init__(self, name, timeoutInSeconds, subsystem: Optional[Any] = ...):
        """Instantiates a TimedCommand with the given name and timeout.

        :param name: the name of the command
        :param timeoutInSeconds: the time the command takes to run
        :param subsystem: the subsystem that this command requires
        """
        ...
    
    def isFinished(self):
        """Ends command when timed out."""
        ...
    


