"""
This type stub file was generated by pyright.
"""

from typing import Optional
from .timedcommand import TimedCommand

"""
This type stub file was generated by pyright.
"""
__all__ = ["WaitCommand"]
class WaitCommand(TimedCommand):
    """A WaitCommand will wait for a certain amount of time before finishing.
    It is useful if you want a :class:`.CommandGroup` to pause for a moment.
    
    .. seealso:: :class:`.CommandGroup`
    """
    def __init__(self, timeout: float, name: Optional[str] = ...) -> None:
        """Instantiates a WaitCommand with the given timeout.
        
        :param timeout: the time the command takes to run (seconds)
        :param name: the name of the command (optional)
        """
        ...
    


