"""
This type stub file was generated by pyright.
"""

from .command import Command

"""
This type stub file was generated by pyright.
"""
__all__ = ["WaitForChildren"]
class WaitForChildren(Command):
    """This command will only finish if whatever :class:`.CommandGroup` it
    is in has no active children.  If it is not a part of a CommandGroup,
    then it will finish immediately.  If it is itself an active child, then
    the CommandGroup will never end.

    This class is useful for the situation where you want to allow anything
    running in parallel to finish, before continuing in the main CommandGroup
    sequence.
    """
    def isFinished(self) -> bool:
        ...
    


