"""
This type stub file was generated by pyright.
"""

class InertialDataIntegrator:
    def __init__(self):
        ...
    
    def updateDisplacement(self, accel_x_g, accel_y_g, update_rate_hz, is_moving):
        ...
    
    def resetDisplacement(self):
        self.displacement = ...
        self.last_velocity = ...
    
    def getVelocityX(self):
        ...
    
    def getVelocityY(self):
        ...
    
    def getVelocityZ(self):
        ...
    
    def getDisplacementX(self):
        ...
    
    def getDisplacementY(self):
        ...
    
    def getDisplacementZ(self):
        ...
    


