"""
This type stub file was generated by pyright.
"""

import enum

__all__ = ["getNavxDigitalChannel", "getNavxPWMChannel", "getNavxAnalogInChannel", "getNavxAnalogOutChannel", "getChannelFromPin", "PinType"]
MAX_NAVX_MXP_DIGIO_PIN_NUMBER = 9
MAX_NAVX_MXP_ANALOGIN_PIN_NUMBER = 3
MAX_NAVX_MXP_ANALOGOUT_PIN_NUMBER = 1
NUM_ROBORIO_ONBOARD_DIGIO_PINS = 10
NUM_ROBORIO_ONBOARD_PWM_PINS = 10
NUM_ROBORIO_ONBOARD_ANALOGIN_PINS = 4
NUM_ROBORIO_ONBOARD_ANALOGOUT_PINS = 2
def getNavxDigitalChannel(pin):
    """Get the WPILib channel number for a digital input on a NavX MXP
    
    :param pin: The NavX pin number (0-9)
    :type pin: int
    
    :returns: RoboRIO channel number
    """
    ...

def getNavxPWMChannel(pin):
    """Get the WPILib channel number for a PWM on a NavX MXP
    
    :param pin: The NavX pin number (0-9)
    :type pin: int
    
    :returns: RoboRIO channel number
    """
    ...

def getNavxAnalogInChannel(pin):
    """Get the WPILib channel number for an Analog Input on a NavX MXP
    
    :param pin: The NavX pin number (0-3)
    :type pin: int
    
    :returns: RoboRIO channel number
    """
    ...

def getNavxAnalogOutChannel(pin):
    """Get the WPILib channel number for an Analog Output on a NavX MXP
    
    :param pin: The NavX pin number (0-1)
    :type pin: int
    
    :returns: RoboRIO channel number
    """
    ...

class PinType(enum.Enum):
    DigitalIO = ...
    PWM = ...
    AnalogIn = ...
    AnalogOut = ...


def getChannelFromPin(pinType, pin):
    """Converts from a NavX MXP pin type and number to the corresponding
    RoboRIO channel number that is used by WPILib.
    
    :param pinType: The type of pin to convert 
    :type pinType: :class:`PinType`
    :param pin: 
    :type pin: int
    
    :returns: RoboRIO channel number
    """
    ...

