"""
This type stub file was generated by pyright.
"""

import logging

logger = logging.getLogger("navx.i2c")
MAX_WPILIB_I2C_READ_BYTES = 127
class RegisterIO_I2C:
    def __init__(self, port):
        self.port = ...
        self.mutex = ...
    
    def init(self):
        ...
    
    def write(self, address, value):
        ...
    
    def read(self, first_address, count):
        ...
    
    def shutdown(self):
        ...
    


