"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Optional

DEFAULT_SPI_BITRATE_HZ = 500000
logger = logging.getLogger("navx.spi")
class RegisterIO_SPI:
    def __init__(self, port, bitrate: Optional[Any] = ...):
        self.port = ...
        self.bitrate = ...
        self.mutex = ...
    
    def init(self):
        ...
    
    def write(self, address, value):
        ...
    
    def read(self, first_address, count):
        ...
    
    def shutdown(self):
        ...
    


