"""
This type stub file was generated by pyright.
"""

from .robotdrivebase import RobotDriveBase
from ..interfaces.speedcontroller import SpeedController
from ..sendablebuilder import SendableBuilder

"""
This type stub file was generated by pyright.
"""
__all__ = ["MecanumDrive"]
class MecanumDrive(RobotDriveBase):
    r"""A class for driving Mecanum drive platforms.

    Mecanum drives are rectangular with one wheel on each corner. Each wheel has rollers toed in
    45 degrees toward the front or back. When looking at the wheels from the top, the roller axles
    should form an X across the robot. Each drive() function provides different inverse kinematic
    relations for a Mecanum drive robot.

    Drive base diagram::

        \_______/
        \ |   | /
          |   |
        /_|___|_\
        /       \


    Each drive() function provides different inverse kinematic relations for a Mecanum drive
    robot. Motor outputs for the right side are negated, so motor direction inversion by the user is
    usually unnecessary.

    This library uses the NED axes convention (North-East-Down as external reference in the world
    frame): http://www.nuclearprojects.com/ins/images/axis_big.png.

    The positive X axis points ahead, the positive Y axis points right, and the positive Z axis
    points down. Rotations follow the right-hand rule, so clockwise rotation around the Z axis is
    positive.

    .. note:: RobotDrive porting guide:

        In MecanumDrive, the right side speed controllers are automatically inverted,
        while in RobotDrive, no speed controllers are automatically inverted.

        :meth:`driveCartesian` is equivalent to :meth:`.RobotDrive.mecanumDrive_Cartesian` if a deadband of 0
        is used, and the ``ySpeed`` and ``gyroAngle`` values are inverted compared to ``RobotDrive`` (i.e
        ``driveCartesian(xSpeed, -ySpeed, zRotation, -gyroAngle)``.

        :meth:`drivePolar` is equivalent to :meth:`.RobotDrive.mecanumPolar` if a deadband of 0 is used.
    """
    instances = ...
    def __init__(self, frontLeftMotor: SpeedController, rearLeftMotor: SpeedController, frontRightMotor: SpeedController, rearRightMotor: SpeedController) -> None:
        """Constructor for MecanumDrive.

        If motors need to be inverted, do so beforehand.
        Motor outputs for the right side are negated, so motor direction inversion
        by the user is usually unnecessary

        :param frontLeftMotor: Front Left Motor
        :param rearLeftMotor: Rear Left Motor
        :param frontRightMotor: Front Right Motor
        :param rearRightMotor: Rear Right Motor
        """
        self.frontLeftMotor = ...
        self.rearLeftMotor = ...
        self.frontRightMotor = ...
        self.rearRightMotor = ...
        self.rightSideInvertMultiplier = ...
        self.reported = ...
    
    def driveCartesian(self, ySpeed: float, xSpeed: float, zRotation: float, gyroAngle: float = ...) -> None:
        """Drive method for Mecanum platform.

        Angles are measured clockwise from the positive X axis. The robot's speed is independent
        from its angle or rotation rate.

        :param ySpeed: The robot's speed along the Y axis [-1.0..1.0]. Right is positive.
        :param xSpeed: The robot's speed along the X axis [-1.0..1.0]. Forward is positive.
        :param zRotation: The robot's rotation rate around the Z axis [-1.0..1.0]. Clockwise is positive.
        :param gyroAngle: The current angle reading from the gyro in degrees around the Z axis. Use
                          this to implement field-oriented controls.
        """
        ...
    
    def drivePolar(self, magnitude: float, angle: float, zRotation: float) -> None:
        """Drive method for Mecanum platform.

        Angles are measured counter-clockwise from straight ahead. The speed at which the robot
        drives (translation) is independent from its angle or rotation rate.

        :param magnitude: The robot's speed at a given angle [-1.0..1.0]. Forward is positive.
        :param angle: The angle around the Z axis at which the robot drives in degrees [-180..180].
        :param zRotation: The robot's rotation rate around the Z axis [-1.0..1.0]. Clockwise is
                          positive.
        """
        ...
    
    def isRightSideInverted(self):
        """
        Gets if the power sent to the right side of the drivetrain is
        multipled by -1.

        :returns: true if the right side is inverted
        """
        ...
    
    def setRightSideInverted(self, rightSideInverted: bool) -> None:
        """
        Sets if the power sent to the right side of the drivetrain should
        be multipled by -1.

        :param rightSideInverted: true if right side power should be multipled
                                  by -1
        """
        self.rightSideInvertMultiplier = ...
    
    def stopMotor(self) -> None:
        ...
    
    def getDescription(self) -> str:
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        ...
    


