"""
This type stub file was generated by pyright.
"""

"""
    Operations related to LEB128 encoding/decoding

    The algorithm is taken from Appendix C of the DWARF 3 spec. For information
    on the encodings refer to section "7.6 - Variable Length Data"

"""
def size_uleb128(value):
    ...

def encode_uleb128(value):
    ...

def read_uleb128(rstream):
    ...

