"""
This type stub file was generated by pyright.
"""

from collections import namedtuple
from typing import Any, Optional

Pair = namedtuple("Pair", ["first", "second"])
def ensure_id_exists(lst, msg_id, default: Optional[Any] = ...):
    ...

