"""
This type stub file was generated by pyright.
"""

from collections import namedtuple

EntryInfo = namedtuple('EntryInfo', ['name', 'type', 'flags'])
ConnectionInfo = namedtuple('ConnectionInfo', ['remote_id', 'remote_ip', 'remote_port', 'last_update', 'protocol_version'])
RpcParamDef = namedtuple('RpcParamDef', ['name', 'def_value'])
RpcResultDef = namedtuple('RpcResultDef', ['name', 'type'])
RpcDefinition = namedtuple('RpcDefinition', ['version', 'name', 'params', 'results'])
RpcCallInfo = namedtuple('RpcCallInfo', ['rpc_id', 'call_uid', 'name', 'params'])
