"""
This type stub file was generated by pyright.
"""

from collections import namedtuple

"""
    Internal storage for ntcore values
    
    Uses namedtuple for efficiency, and because Value objects are supposed
    to be immutable. Will have to measure that and see if there's a performance
    penalty for this in python.
    
    Original ntcore stores the last change time, but it doesn't seem to
    be used anywhere, so we don't store that to make equality comparison
    more efficient.
"""
class Value(namedtuple("Value", ["type", "value"])):
    __slots__ = ...
    @classmethod
    def makeBoolean(cls, value):
        ...
    
    @classmethod
    def makeDouble(cls, value):
        ...
    
    @classmethod
    def makeString(cls, value):
        ...
    
    @classmethod
    def makeRaw(cls, value):
        ...
    
    @classmethod
    def makeBooleanArray(cls, value):
        ...
    
    @classmethod
    def makeDoubleArray(cls, value):
        ...
    
    @classmethod
    def makeStringArray(cls, value):
        ...
    
    @classmethod
    def makeRpc(cls, value):
        ...
    
    @classmethod
    def getFactory(cls, value):
        ...
    
    @classmethod
    def getFactoryByType(cls, type_id):
        ...
    


