"""
This type stub file was generated by pyright.
"""

from .ctre_sim_enums import ErrorCode

class BuffTrajPointStream:
    def __init__(self):
        self.create_called = ...
    
    def _create1(self) -> None:
        self.create_called = ...
    
    def clear(self) -> ErrorCode:
        '''Clear all trajectory points.

        :returns: nonzero error code if operation fails.


        .. note:: This function works on a real robot, but has not yet
                  been implemented in simulation mode. See :ref:`api_support`
                  for more details.

        '''
        ...
    
    def _write(self, position: float, velocity: float, arbFeedFwd: float, auxiliaryPos: float, auxiliaryVel: float, auxiliaryArbFeedFwd: float, profileSlotSelect0: int, profileSlotSelect1: int, isLastPoint: bool, zeroPos: bool, timeDur: int, useAuxPID: bool) -> ErrorCode:
        ...
    


