"""
This type stub file was generated by pyright.
"""

from ..faultsbase import FaultsBase

class CANifierFaults(FaultsBase):
    __slots__ = ...


class CANifierStickyFaults(FaultsBase):
    __slots__ = ...


class Faults(FaultsBase):
    __slots__ = ...
    @property
    def underVoltage(self) -> bool:
        ...
    
    @property
    def forwardLimitSwitch(self) -> bool:
        ...
    
    @property
    def reverseLimitSwitch(self) -> bool:
        ...
    
    @property
    def forwardSoftLimit(self) -> bool:
        ...
    
    @property
    def reverseSoftLimit(self) -> bool:
        ...
    
    @property
    def hardwareFailure(self) -> bool:
        ...
    
    @property
    def resetDuringEn(self) -> bool:
        ...
    
    @property
    def sensorOverflow(self) -> bool:
        ...
    
    @property
    def sensorOutOfPhase(self) -> bool:
        ...
    
    @property
    def hardwareESDReset(self) -> bool:
        ...
    
    @property
    def remoteLossOfSignal(self) -> bool:
        ...
    
    @property
    def apiError(self) -> bool:
        ...
    


class StickyFaults(FaultsBase):
    __slots__ = ...
    @property
    def underVoltage(self) -> bool:
        ...
    
    @property
    def forwardLimitSwitch(self) -> bool:
        ...
    
    @property
    def reverseLimitSwitch(self) -> bool:
        ...
    
    @property
    def forwardSoftLimit(self) -> bool:
        ...
    
    @property
    def reverseSoftLimit(self) -> bool:
        ...
    
    @property
    def resetDuringEn(self) -> bool:
        ...
    
    @property
    def sensorOverflow(self) -> bool:
        ...
    
    @property
    def sensorOutOfPhase(self) -> bool:
        ...
    
    @property
    def hardwareESDReset(self) -> bool:
        ...
    
    @property
    def remoteLossOfSignal(self) -> bool:
        ...
    
    @property
    def apiError(self) -> bool:
        ...
    


class PigeonIMU_Faults(FaultsBase):
    __slots__ = ...


class PigeonIMU_StickyFaults(FaultsBase):
    __slots__ = ...


