"""
This type stub file was generated by pyright.
"""

from hal_impl.i2c_helpers import I2CSimBase
from hal_impl.spi_helpers import SPISimBase

class NavXSimBase:
    """
        This is a really quick hack to get the NavX working in simulation.
        
        If you wish to do more advanced things with this, please add the
        features and make a pull request. :)
    """
    def __init__(self):
        self.cap_flags = ...
        self.timer = ...
    
    def _write(self, data):
        ...
    
    def _read(self, data, count):
        ...
    


class NavXI2CSim(NavXSimBase, I2CSimBase):
    def initializeI2C(self, port, status):
        self.angle_key = ...
    
    def writeI2C(self, port, deviceAddress, dataToSend, sendSize):
        ...
    
    def readI2C(self, port, deviceAddress, buffer, count):
        ...
    


class NavXSPISim(NavXSimBase, SPISimBase):
    def initializeSPI(self, port, status):
        self.angle_key = ...
    
    def writeSPI(self, port, dataToSend, sendSize):
        ...
    
    def transactionSPI(self, port, dataToSend, dataReceived, size):
        ...
    


