"""
This type stub file was generated by pyright.
"""

from .button import Button

"""
This type stub file was generated by pyright.
"""
__all__ = ["InternalButton"]
class InternalButton(Button):
    """This class is intended to be used within a program.  The programmer can
    manually set its value.
    Also includes a setting for whether or not it should invert its value.
    """
    def __init__(self, inverted: bool = ...) -> None:
        """Creates an InternalButton which is inverted depending on the input.

        :param inverted: If False, then this button is pressed when set to
                         True, otherwise it is pressed when set to False.
        """
        self.pressed = ...
        self.inverted = ...
    
    def setInverted(self, inverted: bool) -> None:
        self.inverted = ...
    
    def setPressed(self, pressed: bool) -> None:
        self.pressed = ...
    
    def get(self) -> int:
        ...
    


