"""
This type stub file was generated by pyright.
"""

from .button import Button
from ..interfaces.generichid import GenericHID

"""
This type stub file was generated by pyright.
"""
__all__ = ["JoystickButton"]
class JoystickButton(Button):
    """A :class:`.button.Button` that gets its state from a :class:`.GenericHID`."""
    def __init__(self, joystick: GenericHID, buttonNumber: int) -> None:
        """Create a joystick button for triggering commands.

        :param joystick: The GenericHID object that has the button (e.g.
                         :class:`.Joystick`, :class:`.KinectStick`, etc)
        :param buttonNumber: The button number
                             (see :meth:`.GenericHID.getRawButton`)
        """
        self.joystick = ...
        self.buttonNumber = ...
    
    def get(self) -> bool:
        """Gets the value of the joystick button.

        :returns: The value of the joystick button
        """
        ...
    


