"""
This type stub file was generated by pyright.
"""

from . import data

"""
This type stub file was generated by pyright.
"""
hal_data = data.hal_data
class SerialSimBase:
    """
        Base class to use for Serial protocol simulators
        
        Has all functions that need to be implemented, but throws exceptions
        when data is asked of it. Will throw away set* function data, as most
        low-fidelity simulation will probably not care about such things. 
    """
    def initializeSerialPort(self, port, status):
        self.port = ...
    
    def initializeSerialPortDirect(self, port, portName, status):
        self.port = ...
    
    def setSerialBaudRate(self, port, baud, status):
        ...
    
    def setSerialDataBits(self, port, bits, status):
        ...
    
    def setSerialParity(self, port, parity, status):
        ...
    
    def setSerialStopBits(self, port, stopBits, status):
        ...
    
    def setSerialWriteMode(self, port, mode, status):
        ...
    
    def setSerialFlowControl(self, port, flow, status):
        ...
    
    def setSerialTimeout(self, port, timeout, status):
        ...
    
    def enableSerialTermination(self, port, terminator, status):
        ...
    
    def disableSerialTermination(self, port, status):
        ...
    
    def setSerialReadBufferSize(self, port, size, status):
        ...
    
    def setSerialWriteBufferSize(self, port, size, status):
        ...
    
    def getSerialBytesReceived(self, port, status):
        ...
    
    def readSerial(self, port, buffer, count, status):
        ...
    
    def writeSerial(self, port, buffer, count, status):
        ...
    
    def flushSerial(self, port, status):
        ...
    
    def clearSerial(self, port, status):
        ...
    
    def closeSerial(self, port, status):
        ...
    


