"""
This type stub file was generated by pyright.
"""

from .talonsrx import TalonSRX
from .victorspx import VictorSPX
from .wpi_talonsrx import WPI_TalonSRX
from .wpi_victorspx import WPI_VictorSPX
from .canifier import CANifier
from .pigeonimu import PigeonIMU
from ._impl import ControlMode, ErrorCode, FeedbackDevice, LimitSwitchNormal, LimitSwitchSource, NeutralMode, ParamEnum, RemoteFeedbackDevice, RemoteSensorSource, SetValueMotionProfile
from .btrajectorypoint import BTrajectoryPoint
from .trajectorypoint import TrajectoryPoint

