"""
This type stub file was generated by pyright.
"""

import sys
from collections import namedtuple

__all__ = ["BTrajectoryPoint"]
_name = "BTrajectoryPoint"
_fields = ("position", "velocity", "arbFeedFwd", "auxiliaryPos", "auxiliaryVel", "auxiliaryArbFeedFwd", "profileSlotSelect0", "profileSlotSelect1", "isLastPoint", "zeroPos", "timeDur", "useAuxPID")
_defaults = (0, 0, 0, 0, 0, 0, 0, 0, False, False, 0, False)
if sys.version_info[: 2] >= (3, 7):
    BTrajectoryPoint = namedtuple(_name, _fields, defaults=_defaults)
else:
    BTrajectoryPoint = namedtuple(_name, _fields)
