"""
This type stub file was generated by pyright.
"""

from .basemotorcontroller import BaseMotorController
from ._impl import FeedbackDevice, LimitSwitchSource, StatusFrameEnhanced

__all__ = ["TalonSRX"]
class TalonSRX(BaseMotorController):
    """CTRE Talon SRX Motor Controller when used on CAN Bus.

    Consider using :class:`.WPI_TalonSRX`, which implements various WPILib interfaces.
    """
    FeedbackDevice = ...
    LimitSwitchSource = ...
    StatusFrameEnhanced = ...
    def __init__(self, deviceNumber: int) -> None:
        ...
    


