"""
This type stub file was generated by pyright.
"""

from ..command.subsystem import Subsystem
from ..sendable import Sendable
from ..sendablebuilder import SendableBuilder

"""
This type stub file was generated by pyright.
"""
__all__ = ["NamedSendable"]
class NamedSendable(Sendable):
    """The interface for sendable objects that gives the sendable a default
    name in the Smart Dashboard.

    .. deprecated:: 2018.0
        Use :class:`.Sendable` directly instead.
    """
    def __init_subclass__(cls, **kwargs) -> None:
        ...
    
    def getName(self) -> str:
        """The name of the subtable.

        :returns: The name of the subtable of SmartDashboard that the
                  :class:`.Sendable` object will use
        """
        ...
    
    def setName(self, name: str) -> None:
        ...
    
    def getSubsystem(self) -> str:
        ...
    
    def setSubsystem(self, subsystem: Subsystem) -> None:
        ...
    
    def initSendable(self, builder: SendableBuilder) -> None:
        ...
    


