"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__all__ = ["PIDOutput"]
class PIDOutput:
    """This interface allows :class:`.PIDController` to write its results to
    its output.
    """
    def pidWrite(self, output: float) -> None:
        """Set the output to the value calculated by :class:`.PIDController`.

        :param output: the value calculated by PIDController
        """
        ...
    


