"""
This type stub file was generated by pyright.
"""

from .pidsource import PIDSource

"""
This type stub file was generated by pyright.
"""
__all__ = ["Potentiometer"]
class Potentiometer(PIDSource):
    """Interface for a Potentiometer."""
    def get(self) -> float:
        ...
    


