"""
This type stub file was generated by pyright.
"""

from .pidoutput import PIDOutput

"""
This type stub file was generated by pyright.
"""
__all__ = ["SpeedController"]
class SpeedController(PIDOutput):
    """Interface for speed controlling devices."""
    def set(self, speed: float) -> None:
        """Common interface for setting the speed of a speed controller.

        :param speed: The speed to set.  Value should be between -1.0 and 1.0.
        """
        ...
    
    def get(self) -> float:
        """Common interface for getting the current set speed of a speed
        controller.

        :returns: The current set speed.  Value is between -1.0 and 1.0.
        """
        ...
    
    def setInverted(self, isInverted: bool) -> None:
        """Common interface for inverting direction of a speed controller.

        :param isInverted: The state of inversion
        """
        ...
    
    def getInverted(self) -> bool:
        """Common interface for determining if a speed controller is in the
        inverted state or not.

        :returns: True if in inverted state
        """
        ...
    
    def disable(self) -> None:
        """Disable the speed controller."""
        ...
    
    def stopMotor(self) -> None:
        """Stops motor movement. Motor can be moved again by calling set without having
        to re-enable the motor.
        """
        ...
    


