"""
This type stub file was generated by pyright.
"""

class FaultsBase:
    __slots__ = ...
    def __init__(self, bits: int = ...) -> None:
        self.bits = ...
    
    def toBitfield(self) -> int:
        ...
    
    def hasAnyFault(self) -> bool:
        """True iff any of the flags are true."""
        ...
    
    def __str__(self):
        ...
    


