"""
This type stub file was generated by pyright.
"""

from collections import namedtuple

__all__ = ["MotionProfileStatus"]
MotionProfileStatus = namedtuple("MotionProfileStatus", ["topBufferRem", "topBufferCnt", "btmBufferCnt", "hasUnderrun", "isUnderrun", "activePointValid", "isLast", "profileSlotSelect0", "outputEnable", "timeDurMs", "profileSlotSelect1"])
